
// This file has been generated by the GUI designer. Do not modify.
namespace NScumm.GL
{
	public partial class MenuWindow
	{
		private global::Gtk.VButtonBox vbuttonbox1;
		private global::Gtk.Button btnLoad;
		private global::Gtk.Button btnSave;
		private global::Gtk.Button btnQuit;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NScumm.GL.MenuWindow
			this.Name = "NScumm.GL.MenuWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Menu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(14));
			// Container child NScumm.GL.MenuWindow.Gtk.Container+ContainerChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnLoad = new global::Gtk.Button ();
			this.btnLoad.CanFocus = true;
			this.btnLoad.Name = "btnLoad";
			this.btnLoad.UseUnderline = true;
			this.btnLoad.Label = global::Mono.Unix.Catalog.GetString ("Load");
			this.vbuttonbox1.Add (this.btnLoad);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnLoad]));
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.vbuttonbox1.Add (this.btnSave);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnSave]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuit = new global::Gtk.Button ();
			this.btnQuit.CanFocus = true;
			this.btnQuit.Name = "btnQuit";
			this.btnQuit.UseUnderline = true;
			this.btnQuit.Label = global::Mono.Unix.Catalog.GetString ("Quit");
			this.vbuttonbox1.Add (this.btnQuit);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnQuit]));
			w3.Secondary = true;
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(10));
			this.Add (this.vbuttonbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 180;
			this.DefaultHeight = 130;
			this.Show ();
		}
	}
}
